name: pusher
description: Unofficial Flutter plugin for Pusher
version: 0.0.1
repository: https://github.com/amanzdev/flutter_pusher

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4

flutter:
  plugin:
    platforms:
      android:
        package: my.amanz.pusher
        pluginClass: PusherPlugin
      ios:
        pluginClass: PusherPlugin
